import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    'nav.features': 'Features',
    'nav.about': 'About',
    'nav.analytics': 'Analytics',
    'nav.integrations': 'Integrations',
    'nav.pricing': 'Pricing',
    'nav.contact': 'Contact',
    'nav.panel': 'Panel',
    'nav.freeTrial': 'Free Trial',

    // Hero Section
    'hero.badge': 'AI-Powered Retail Analytics Platform',
    'hero.title': 'AI-Powered',
    'hero.subtitle': 'Retail Analytics',
    'hero.description': 'Transform your retail operations, maximize sales and customer satisfaction with advanced AI analytics.',
    'hero.tagline': 'Track customer behavior, optimize store performance, and increase sales with real-time insights.',
    'hero.startTrial': 'Start Free Trial',
    'hero.watchDemo': 'Watch',
    'hero.accuracy': 'Accuracy',
    'hero.realTime': 'Real-time',
    'hero.stores': 'Active Stores',

    // Features
    'features.badge': 'Core Technology',
    'features.title': 'Comprehensive Retail Analytics',
    'features.subtitle': 'Everything you need to optimize your retail operations',

    // Retail Features
    'retail.badge': 'Retail Analytics Features',
    
    'features.queue.title': 'Queue Management & Customer Flow Optimization',
    'features.queue.description': '• Real-time customer density monitoring and queue analysis\n• Optimize staff allocation during peak hours\n• Minimize wait times and maximize satisfaction\n• Instant notifications for critical situations\n• Prevent lost sales with proactive management',

    'features.cashier.title': 'Cashier Performance Analytics & Efficiency Management',
    'features.cashier.description': '• Detailed checkout point performance analysis\n• Track service times and processing speed\n• Measure cashier productivity with precision\n• Monitor customer satisfaction metrics\n• Identify training needs and improvement areas',

    'features.heatmap.title': 'Advanced Heat Mapping & Movement Analytics',
    'features.heatmap.description': '• Visualize customer movements and traffic patterns\n• Analyze most-visited zones and dwell points\n• Optimize product placement and promotional areas\n• Data-driven store layout decisions\n• Track seasonal changes and campaign impacts',

    'features.demographics.title': 'Customer Demographics Analysis & Segmentation',
    'features.demographics.description': '• GDPR/KVKK compliant demographic analysis\n• Track age, gender, and visit frequency patterns\n• Clarify target audience profiles\n• Personalize marketing strategies\n• Dynamic inventory planning based on demographics',

    'features.staff.title': 'Staff Productivity Analytics & Workforce Optimization',
    'features.staff.description': '• Objective performance evaluation with data\n• Analyze shift efficiency and task distribution\n• Forecast staffing needs in advance\n• Optimize workforce costs\n• Performance-based management systems',

    'features.campaigns.title': 'Campaign Performance Analytics & ROI Measurement',
    'features.campaigns.description': '• Detailed campaign effectiveness analysis\n• Measure ROI and conversion rates\n• Track customer engagement metrics\n• Compare pre, during, and post-campaign performance\n• Predictive recommendations for future campaigns',

    // Use Cases
    'useCases.badge': 'Success Stories',
    'useCases.title': 'Real-World Applications',
    'useCases.subtitle': 'See how Vislivis transforms retail operations in practice',
    'useCases.scenario1.title': 'Peak Hours Cashier Optimization',
    'useCases.scenario1.description': 'Predict busiest hours with queue management and ensure adequate cashier availability to boost customer satisfaction.',
    'useCases.scenario1.metric1': '40% reduction in wait times',
    'useCases.scenario1.metric2': 'Improved customer satisfaction',
    'useCases.scenario1.metric3': 'Optimized staff allocation',
    'useCases.scenario2.title': 'Promotion Effectiveness Measurement',
    'useCases.scenario2.description': 'Instantly see the impact of new products or discounts on in-store traffic and sales with campaign analysis.',
    'useCases.scenario2.metric1': 'Real-time campaign tracking',
    'useCases.scenario2.metric2': 'Instant ROI measurement',
    'useCases.scenario2.metric3': 'Traffic pattern analysis',
    'useCases.scenario3.title': 'Inventory Optimization',
    'useCases.scenario3.description': 'Combine sales and behavior data to identify fast-moving products and stock-out risks for better inventory management.',
    'useCases.scenario3.metric1': 'Reduced stockouts by 30%',
    'useCases.scenario3.metric2': 'Optimized inventory levels',
    'useCases.scenario3.metric3': 'Predictive restocking',

    // Analytics Dashboard
    'analytics.badge': 'Advanced Analytics',
    'analytics.title': 'Advanced Analytics Dashboard',
    'analytics.subtitle': 'Real-time insights and historical data analysis',
    'analytics.description': 'Our comprehensive dashboard provides detailed insights into your retail operations with comparative analysis and predictive recommendations.',

    'analytics.comparison.title': 'Period Comparison & Change Tracking',
    'analytics.comparison.description': '• Track KPI changes with percentage indicators (▲ %8 or ▼ %5)\n• Compare vs. previous day, last week, and last year\n• Comprehensive trend analysis and pattern recognition',

    'analytics.products.title': 'Product Analytics & Performance Tracking',
    'analytics.products.description': '• Track customer engagement and trial behaviors\n• Identify top-performing SKUs and interaction patterns\n• Measure product dwell time and interaction frequency\n• Monitor conversion funnels from touch to purchase\n• Optimize product placement with data-driven insights',

    'analytics.kpi.title': 'KPI Dashboard & Sales Conversion Analytics',
    'analytics.kpi.description': '• Real-time visibility into critical business metrics\n• Track conversion rates and transaction values\n• Analyze basket size and customer acquisition costs\n• Benchmark against historical data and targets\n• Advanced segmentation by time, product, and location',

    'analytics.weather.title': 'Weather Intelligence & Predictive Planning',
    'analytics.weather.description': '• 15-day weather forecasting with retail impact analysis\n• Automated alerts for conditions affecting foot traffic\n• Proactive staffing and inventory adjustments\n• Historical correlation analysis for seasonal patterns\n• Optimize promotions based on weather predictions',

    'analytics.ai.title': 'AI-Powered Predictive Intelligence & Recommendations',
    'analytics.ai.description': '• ML engine generates actionable insights with NLP\n• Identify hidden patterns and predict future trends\n• Optimal strategies for inventory and staffing\n• Contextual insights from multiple data variables\n• Prescriptive recommendations for performance gains',

    'analytics.metrics.trafficIncrease': 'Daily Traffic Increase',
    'analytics.metrics.processing': 'Real-time Processing',
    'analytics.metrics.uptime': 'Uptime Guarantee',
    'analytics.metrics.monitoring': 'Continuous Monitoring',

    // Advanced Features
    'advanced.badge': 'Enterprise Solutions',
    'advanced.title': 'Advanced Enterprise Features',
    'advanced.subtitle': 'Comprehensive solutions for modern retail operations',
    'advanced.inventory.title': 'Inventory Management Integration',
    'advanced.inventory.description': 'Optimize stock management by combining sales and behavior data to identify fast-moving products and stock-out risks.',
    'advanced.inventory.benefit1': 'Reduce stockouts by 30%',
    'advanced.inventory.benefit2': 'Optimize inventory turnover',
    'advanced.inventory.benefit3': 'Predictive restocking alerts',
    'advanced.inventory.benefit4': 'Demand forecasting',
    'advanced.security.title': 'Advanced Security & Privacy',
    'advanced.security.description': 'GDPR/KVKK compliant data processing with advanced anonymization and enterprise-grade security protocols.',
    'advanced.security.benefit1': 'GDPR/KVKK compliance',
    'advanced.security.benefit2': 'Advanced data anonymization',
    'advanced.security.benefit3': 'Enterprise-grade encryption',
    'advanced.security.benefit4': 'Audit trail logging',
    'advanced.multistore.title': 'Multi-Store Management',
    'advanced.multistore.description': 'Manage multiple store performance from a single dashboard, compare locations and identify best practices.',
    'advanced.multistore.benefit1': 'Centralized management',
    'advanced.multistore.benefit2': 'Cross-location analytics',
    'advanced.multistore.benefit3': 'Performance benchmarking',
    'advanced.multistore.benefit4': 'Best practice identification',

    // Integrations
    'integrations.badge': 'System Integrations',
    'integrations.title': 'Seamless Integrations',
    'integrations.subtitle': 'Connect with your existing retail systems',
    'integrations.crm.title': 'CRM Integration',
    'integrations.crm.description': 'Sync customer data with your existing CRM systems',
    'integrations.erp.title': 'ERP Integration',
    'integrations.erp.description': 'Connect with enterprise resource planning systems',
    'integrations.pos.title': 'POS Integration',
    'integrations.pos.description': 'Direct integration with cash register and point-of-sale systems',
    'integrations.marketing.title': 'Marketing Automation',
    'integrations.marketing.description': 'Connect customer behavior data with marketing platforms for targeted campaigns',
    'integrations.bi.title': 'Business Intelligence',
    'integrations.bi.description': 'Integrate with BI and data visualization tools for advanced analytics',
    'integrations.hris.title': 'HRIS & DMS Integration',
    'integrations.hris.description': 'Integrate with human resources and document management systems to evaluate staff performance from a broader perspective with leave data, shift changes, and performance reviews',
    'integrations.capabilities.title': 'Advanced Integration Capabilities',
    'integrations.capabilities.description': 'Powerful and well-documented APIs enable seamless integration with your existing business systems, providing a unified view of your retail operations.',
    'integrations.api.title': 'RESTful APIs',
    'integrations.api.description': 'Powerful and well-documented APIs for custom integrations',
    'integrations.webhook.title': 'Webhook Support',
    'integrations.webhook.description': 'Real-time event notifications for system synchronization',
    'integrations.formats.title': 'Data Formats',
    'integrations.formats.description': 'Industry standard JSON and CSV formats for flexibility',
    'integrations.security.title': 'Enterprise Security',
    'integrations.security.description': 'Advanced encryption and security protocols',

    // Mobile
    'mobile.badge': 'Mobile Experience',
    'mobile.title': 'Mobile Analytics',
    'mobile.subtitle': 'Monitor your stores from anywhere',
    'mobile.description': 'Access real-time analytics and receive instant notifications on your mobile device.',
    'mobile.notifications': 'Real-time Notifications',
    'mobile.notifications.description': 'Get instant alerts for queue buildups, staff productivity changes, and sales anomalies',
    'mobile.monitoring': 'Live Store Monitoring',
    'mobile.monitoring.description': 'Monitor live store analytics, heat maps, and customer flow from anywhere',
    'mobile.reports': 'Mobile Reports',
    'mobile.reports.description': 'Access detailed analytics reports and KPI dashboards on mobile',
    'mobile.alerts': 'Custom Alerts',
    'mobile.alerts.description': 'Set custom alerts for specific retail metrics and thresholds',
    'mobile.distribution.title': 'Enterprise Distribution',
    'mobile.distribution.description': 'Applications are distributed through enterprise channels with custom branding and configuration options available for large deployments.',
    'mobile.distribution.ios': 'iOS 14.0+ supported',
    'mobile.distribution.android': 'Android 9.0+ supported',
    'mobile.distribution.mdm': 'Enterprise MDM compatible',
    'mobile.distribution.branding': 'Custom branding available',
    'mobile.distribution.button': 'Request Enterprise Access',

    // Pricing
    'pricing.badge': 'Flexible Solutions',
    'pricing.title': 'Flexible Pricing Plans',
    'pricing.subtitle': 'Choose the perfect plan for your retail business',
    'pricing.starter': 'Starter',
    'pricing.starter.description': 'Perfect for small retail stores getting started with analytics',
    'pricing.starter.feature1': 'Up to 2 store locations',
    'pricing.starter.feature2': 'Basic analytics dashboard',
    'pricing.starter.feature3': 'Queue management',
    'pricing.starter.feature4': 'Customer demographics',
    'pricing.starter.feature5': 'Email notifications',
    'pricing.starter.feature6': 'Business hours support',
    'pricing.professional': 'Professional',
    'pricing.professional.description': 'Advanced analytics for growing retail businesses',
    'pricing.professional.feature1': 'Up to 10 store locations',
    'pricing.professional.feature2': 'Advanced heat maps',
    'pricing.professional.feature3': 'Staff productivity tracking',
    'pricing.professional.feature4': 'Campaign analysis',
    'pricing.professional.feature5': 'Weather integration',
    'pricing.professional.feature6': 'Mobile app access',
    'pricing.professional.feature7': 'Priority 24/7 support',
    'pricing.professional.feature8': 'CRM/ERP integrations',
    'pricing.enterprise': 'Enterprise',
    'pricing.enterprise.description': 'Complete retail analytics solution for large chains',
    'pricing.enterprise.feature1': 'Unlimited store locations',
    'pricing.enterprise.feature2': 'AI-powered recommendations',
    'pricing.enterprise.feature3': 'Advanced KPI tracking',
    'pricing.enterprise.feature4': 'Custom integrations',
    'pricing.enterprise.feature5': 'On-premises deployment',
    'pricing.enterprise.feature6': 'Dedicated support team',
    'pricing.enterprise.feature7': 'White-label options',
    'pricing.enterprise.feature8': 'Advanced security',
    'pricing.enterprise.feature9': 'Custom reporting',
    'pricing.contactSales': 'Contact Sales',
    'pricing.scheduleDemo': 'Schedule Demo',
    'pricing.requestInfo': 'Request Information',
    'pricing.mostPopular': 'Most Popular',
    'pricing.custom': 'Custom',
    'pricing.custom.title': 'Custom Enterprise Solutions',
    'pricing.custom.description': 'All plans include professional installation, training, and ongoing support. Pricing varies based on deployment size and specific requirements.',
    'pricing.custom.benefit1': 'Professional Installation',
    'pricing.custom.benefit2': '24/7 Technical Support',
    'pricing.custom.benefit3': 'Flexible Contracts',

    // Testimonials
    'testimonials.title': 'Trusted by Retailers',
    'testimonials.subtitle': 'See how leading retail brands use Vislivis',
    'testimonials.stats.clients': 'Enterprise Clients',
    'testimonials.stats.uptime': 'System Uptime',
    'testimonials.stats.support': 'Support Coverage',
    'testimonials.stats.response': 'Response Time',

    // FAQ
    'faq.badge': 'Support & Information',
    'faq.title': 'Frequently Asked Questions',
    'faq.questions': 'Still have questions?',
    'faq.contactTeam': 'Contact Our Team',
    'faq.subtitle': 'Everything you need to know about Vislivis',
    'faq.q1': 'How long does installation take?',
    'faq.a1': 'Professional installation typically takes half a day depending on store size and camera count.',
    'faq.q2': 'Which cameras are compatible?',
    'faq.a2': 'Vislivis integrates with all camera brands and models. Minimum requirement: 2MP IP camera.',
    'faq.q3': 'How long is data stored?',
    'faq.a3': 'All data is processed locally without external image transmission. Analytics data is stored for up to 2 years with flexible retention policies.',
    'faq.q4': 'Is the system GDPR compliant?',
    'faq.a4': 'Yes, all data processing is GDPR/KVKK compliant with advanced anonymization and privacy protection.',
    'faq.q5': 'Can I manage multiple stores?',
    'faq.a5': 'Yes, our platform supports unlimited stores with centralized management and cross-location analytics.',
    'faq.q6': 'What kind of support is provided?',
    'faq.a6': '24/7 technical support, regular system updates, and dedicated account management for enterprise clients.',
    'faq.q7': 'Do I need additional hardware besides cameras?',
    'faq.a7': 'A recording server is required where camera footage is stored. Server requirements vary based on camera count and modules used. Please contact us for detailed specifications.',
    'faq.q8': 'What is the system accuracy rate?',
    'faq.a8': 'The system operates with over 90% accuracy on average. With initial setup calibration using store footage, this rate can be improved further.',

    // Contact
    'contact.title': 'Get Started Today',
    'contact.subtitle': 'Ready to transform your retail operations? Contact us for a personalized demo.',
    'contact.getInTouch': 'Get in Touch',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.address': 'Address',
    'contact.sendMessage': 'Send a Message',
    'contact.name': 'Name',
    'contact.company': 'Company',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.hours.title': 'Business Hours',
    'contact.hours.weekday': 'Monday - Friday',
    'contact.hours.weekdayTime': '9:00 AM - 6:00 PM EST',
    'contact.hours.saturday': 'Saturday',
    'contact.hours.saturdayTime': '10:00 AM - 4:00 PM EST',
    'contact.hours.sunday': 'Sunday',
    'contact.hours.sundayTime': 'Closed',
    'contact.hours.emergency': 'Emergency Support',
    'contact.hours.emergencyTime': '24/7 Available',
    'contact.response': 'We typically respond within 24 hours. For urgent matters, please call directly.',

    // Footer
    'footer.description': 'AI-powered retail analytics platform helping businesses optimize operations and increase sales.',
    'footer.products': 'Products',
    'footer.support': 'Support',
    'footer.company': 'Company',
    'footer.certifications': 'Our Certifications',
    'footer.rights': '© 2024 Vislivis. All rights reserved.',
    'footer.products.queue': 'Queue Management',
    'footer.products.cashier': 'Cashier Analytics',
    'footer.products.behavior': 'Customer Behavior',
    'footer.products.heatmap': 'Store Heatmaps',
    'footer.support.docs': 'Documentation',
    'footer.support.center': 'Support Center',
    'footer.support.contact': 'Contact',
    'footer.support.status': 'System Status',
    'footer.company.about': 'About Us',
    'footer.company.careers': 'Careers',
    'footer.company.blog': 'Blog',
    'footer.company.partners': 'Partners',

    // About Section
    'about.title': 'About Vislivis',
    'about.subtitle': 'Transforming retail operations with cutting-edge AI technology',
    
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'We set out with the mission to transform the retail sector with the power of AI. Our goal is to help businesses optimize their operations, increase sales, and enhance customer satisfaction through data-driven insights.',
    
    'about.vision.title': 'Our Vision',
    'about.vision.description': 'To become the global leader in AI-powered retail analytics, making advanced technology accessible to businesses of all sizes and revolutionizing how retailers understand and serve their customers.',
    
    'about.story.title': 'Our Story',
    'about.story.paragraph1': 'Vislivis was founded in 2020 by a team of AI researchers and retail industry veterans who recognized the untapped potential of computer vision in retail environments.',
    'about.story.paragraph2': 'Starting with a simple observation that traditional retail analytics were missing crucial behavioral insights, we developed proprietary AI algorithms that could understand customer patterns in ways never before possible.',
    'about.story.paragraph3': 'Today, we serve over 500 retail locations worldwide, helping businesses make smarter decisions through real-time analytics and predictive insights.',
    
    'about.values.title': 'Our Values',
    'about.values.subtitle': 'The principles that guide everything we do',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.description': 'Continuously pushing the boundaries of AI technology to solve real retail challenges.',
    'about.values.customer.title': 'Customer Focus',
    'about.values.customer.description': 'Every feature we build is designed with our customers\' success in mind.',
    'about.values.reliability.title': 'Reliability',
    'about.values.reliability.description': 'Delivering consistent, accurate results that businesses can depend on.',
    'about.values.growth.title': 'Growth',
    'about.values.growth.description': 'Helping our clients achieve sustainable growth through data-driven insights.',
    
    'about.why.title': 'Why Choose Vislivis?',
    'about.why.subtitle': 'What sets us apart in the retail analytics landscape',
    'about.differentiators.accuracy': 'AI Accuracy',
    'about.differentiators.speed': 'Processing Speed',
    'about.differentiators.stores': 'Active Stores',
    'about.differentiators.support': 'Support Coverage',
    
    'about.team.title': 'Meet Our Team',
    'about.team.subtitle': 'The experts behind Vislivis technology',
    
    'about.awards.title': 'Awards & Recognition',

    // Live Support
    'support.title': 'Live Support',
    'support.online': 'Online now',
    'support.welcome': 'Hello! How can we help you with Vislivis today?',
    'support.autoResponse': 'Thank you for your message. Our team will get back to you shortly. For immediate assistance, please call 0216 451 91 12.',
    'support.placeholder': 'Type your message...',

    // Terms of Service
    'terms.title': 'Terms of Service',
    'terms.lastUpdated': 'Last Updated',
    'terms.date': 'January 1, 2025',
    'terms.acceptance.title': '1. Acceptance of Terms',
    'terms.acceptance.content': 'By accessing and using Vislivis services, you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.',
    'terms.services.title': '2. Description of Services',
    'terms.services.content': 'Vislivis provides AI-powered retail analytics solutions including customer behavior tracking, queue management, product analytics, and business intelligence tools. Our services are provided on a subscription basis and may be updated or modified from time to time.',
    'terms.userResponsibilities.title': '3. User Responsibilities',
    'terms.userResponsibilities.content': 'As a user of Vislivis services, you agree to:',
    'terms.userResponsibilities.item1': 'Provide accurate and complete information during registration',
    'terms.userResponsibilities.item2': 'Maintain the security of your account credentials',
    'terms.userResponsibilities.item3': 'Use the services in compliance with all applicable laws and regulations',
    'terms.userResponsibilities.item4': 'Not attempt to compromise the security or integrity of our systems',
    'terms.intellectualProperty.title': '4. Intellectual Property Rights',
    'terms.intellectualProperty.content': 'All content, software, technology, and materials provided through Vislivis services are the exclusive property of Vislivis and are protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works without explicit written permission.',
    'terms.dataPrivacy.title': '5. Data Privacy and Security',
    'terms.dataPrivacy.content': 'We are committed to protecting your data privacy. Our collection, use, and protection of personal data are governed by our Privacy Policy. By using our services, you consent to our data practices as described in the Privacy Policy.',
    'terms.limitation.title': '6. Limitation of Liability',
    'terms.limitation.content': 'Vislivis shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use our services. Our total liability shall not exceed the amount paid by you for the services in the twelve months preceding the claim.',
    'terms.termination.title': '7. Termination',
    'terms.termination.content': 'We reserve the right to suspend or terminate your access to our services at any time for violation of these terms or for any other reason deemed necessary. Upon termination, your right to use the services will immediately cease.',
    'terms.changes.title': '8. Changes to Terms',
    'terms.changes.content': 'We reserve the right to modify these Terms of Service at any time. We will notify users of significant changes via email or through our platform. Continued use of services after changes constitutes acceptance of the modified terms.',
    'terms.contact.title': '9. Contact Information',
    'terms.contact.content': 'If you have any questions about these Terms of Service, please contact us:',

    // Privacy Policy
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last Updated',
    'privacy.date': 'January 1, 2025',
    'privacy.introduction.title': '1. Introduction',
    'privacy.introduction.content': 'At Vislivis, we take your privacy seriously. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our retail analytics platform and services.',
    'privacy.dataCollection.title': '2. Information We Collect',
    'privacy.dataCollection.content': 'We collect several types of information to provide and improve our services:',
    'privacy.dataCollection.item1': 'Account Information: Name, email address, company details, and contact information',
    'privacy.dataCollection.item2': 'Usage Data: Information about how you interact with our services',
    'privacy.dataCollection.item3': 'Analytics Data: Customer behavior patterns, store performance metrics, and operational data',
    'privacy.dataCollection.item4': 'Technical Data: IP addresses, browser types, device information, and system logs',
    'privacy.dataCollection.item5': 'Camera Data: Video footage and derived analytics data from retail cameras',
    'privacy.dataUsage.title': '3. How We Use Your Information',
    'privacy.dataUsage.content': 'We use collected information for the following purposes:',
    'privacy.dataUsage.item1': 'Providing and maintaining our services',
    'privacy.dataUsage.item2': 'Improving and personalizing user experience',
    'privacy.dataUsage.item3': 'Communicating with you about services, updates, and support',
    'privacy.dataUsage.item4': 'Analyzing usage patterns to enhance service quality',
    'privacy.dataSharing.title': '4. Data Sharing and Disclosure',
    'privacy.dataSharing.content': 'We do not sell your personal information. We may share data with trusted service providers who assist in operating our platform, conducting business, or serving our users, subject to confidentiality agreements. We may also disclose information when required by law or to protect our rights.',
    'privacy.dataSecurity.title': '5. Data Security',
    'privacy.dataSecurity.content': 'We implement industry-standard security measures to protect your data, including encryption, secure servers, and access controls. However, no method of transmission over the internet is 100% secure, and we cannot guarantee absolute security.',
    'privacy.dataRetention.title': '6. Data Retention',
    'privacy.dataRetention.content': 'We retain personal data for as long as necessary to provide services and fulfill the purposes outlined in this policy. Analytics data may be retained longer for historical analysis and reporting purposes, in accordance with applicable laws.',
    'privacy.userRights.title': '7. Your Rights',
    'privacy.userRights.content': 'You have the following rights regarding your personal data:',
    'privacy.userRights.item1': 'Access: Request access to your personal data',
    'privacy.userRights.item2': 'Correction: Request correction of inaccurate data',
    'privacy.userRights.item3': 'Deletion: Request deletion of your personal data',
    'privacy.userRights.item4': 'Data Portability: Request a copy of your data in a structured format',
    'privacy.cookies.title': '8. Cookies and Tracking Technologies',
    'privacy.cookies.content': 'We use cookies and similar tracking technologies to track activity on our services and hold certain information. You can instruct your browser to refuse cookies or to indicate when a cookie is being sent. Please see our Cookie Policy for more details.',
    'privacy.changes.title': '9. Changes to Privacy Policy',
    'privacy.changes.content': 'We may update this Privacy Policy from time to time. We will notify you of changes by posting the new policy on this page and updating the "Last Updated" date. Significant changes will be communicated via email.',
    'privacy.contact.title': '10. Contact Us',
    'privacy.contact.content': 'If you have questions or concerns about this Privacy Policy or our data practices, please contact us:',

    // Cookie Policy
    'cookie.title': 'Cookie Policy',
    'cookie.lastUpdated': 'Last Updated',
    'cookie.date': 'January 1, 2025',
    'cookie.what.title': '1. What Are Cookies',
    'cookie.what.content': 'Cookies are small text files stored on your device when you visit websites. They help websites remember your preferences and improve your browsing experience. Vislivis uses cookies to enhance functionality, analyze usage, and provide personalized experiences.',
    'cookie.types.title': '2. Types of Cookies We Use',
    'cookie.types.content': 'We use different types of cookies for various purposes:',
    'cookie.types.essential.title': 'Essential Cookies',
    'cookie.types.essential.content': 'Required for the website to function properly. These enable core functionality such as security, authentication, and accessibility features. Without these cookies, certain services cannot be provided.',
    'cookie.types.performance.title': 'Performance Cookies',
    'cookie.types.performance.content': 'Help us understand how visitors interact with our website by collecting and reporting information anonymously. This data helps us improve website functionality and user experience.',
    'cookie.types.functional.title': 'Functional Cookies',
    'cookie.types.functional.content': 'Enable enhanced functionality and personalization, such as remembering your preferences, language settings, and user interface customizations.',
    'cookie.types.analytics.title': 'Analytics Cookies',
    'cookie.types.analytics.content': 'Allow us to recognize and count visitors, understand how visitors move around our website, and identify which pages are most and least popular. This helps us optimize content and navigation.',
    'cookie.usage.title': '3. How We Use Cookies',
    'cookie.usage.content': 'Vislivis uses cookies to:',
    'cookie.usage.item1': 'Authenticate users and maintain secure sessions',
    'cookie.usage.item2': 'Remember user preferences and settings',
    'cookie.usage.item3': 'Analyze website traffic and usage patterns',
    'cookie.usage.item4': 'Improve website performance and functionality',
    'cookie.thirdParty.title': '4. Third-Party Cookies',
    'cookie.thirdParty.content': 'Some cookies are placed by third-party services that appear on our pages. We use trusted third parties for analytics and performance monitoring. These third parties have their own privacy policies, and we have no control over their cookies.',
    'cookie.control.title': '5. Managing Cookies',
    'cookie.control.content': 'You have several options to manage or disable cookies:',
    'cookie.control.item1': 'Browser Settings: Most browsers allow you to refuse cookies or delete existing ones through settings',
    'cookie.control.item2': 'Cookie Preferences: Use our cookie consent tool to customize your preferences',
    'cookie.control.item3': 'Opt-Out Tools: Use third-party opt-out tools for analytics and advertising cookies',
    'cookie.changes.title': '6. Changes to Cookie Policy',
    'cookie.changes.content': 'We may update this Cookie Policy to reflect changes in our practices or for operational, legal, or regulatory reasons. Please review this policy periodically for updates.',
    'cookie.contact.title': '7. Contact Us',
    'cookie.contact.content': 'If you have questions about our use of cookies or this Cookie Policy, please contact us:',
  },
  tr: {
    // Header
    'nav.features': 'Özellikler',
    'nav.about': 'Hakkımızda',
    'nav.analytics': 'Analitik',
    'nav.integrations': 'Entegrasyonlar',
    'nav.pricing': 'Fiyatlandırma',
    'nav.contact': 'İletişim',
    'nav.panel': 'Panel',
    'nav.freeTrial': 'Ücretsiz Dene',

    // Hero Section
    'hero.badge': 'AI Destekli Retail Analitik Platformu',
    'hero.title': 'AI Destekli',
    'hero.subtitle': 'Retail Analitik',
    'hero.description': 'Retail operasyonlarınızı dönüştürün, satışları ve müşteri memnuniyetini maksimize edin.',
    'hero.tagline': 'Müşteri davranışlarını takip edin, mağaza performansını optimize edin ve gerçek zamanlı içgörülerle satışları artırın.',
    'hero.startTrial': 'Ücretsiz Deneyin',
    'hero.watchDemo': 'İzleyin',
    'hero.accuracy': 'Doğruluk',
    'hero.realTime': 'Gerçek Zamanlı',
    'hero.stores': 'Aktif Mağaza',

    // Features
    'features.badge': 'Temel Teknoloji',
    'features.title': 'Kapsamlı Retail Analitik',
    'features.subtitle': 'Retail operasyonlarınızı optimize etmek için ihtiyacınız olan her şey',

    // Retail Features
    'retail.badge': 'Retail Analitik Özellikleri',
    
    'features.queue.title': 'Kuyruk Yönetimi ve Müşteri Akış Optimizasyonu',
    'features.queue.description': '• Gerçek zamanlı müşteri yoğunluğu izleme ve kuyruk analizi\n• Yoğun saatlerde personel planlamasını optimize etme\n• Bekleme sürelerini minimize ve memnuniyeti maksimize etme\n• Kritik durumlar için anlık bildirimler\n• Proaktif yönetim ile kayıp satışları önleme',

    'features.cashier.title': 'Kasa Performans Analizi ve Verimlilik Yönetimi',
    'features.cashier.description': '• Detaylı kasa noktası performans analizi\n• Servis süreleri ve işleme hızını takip etme\n• Kasiyer verimliğini hassas ölçümleme\n• Müşteri memnuniyet metriklerini izleme\n• Eğitim ihtiyaçları ve iyileştirme alanlarını belirleme',

    'features.heatmap.title': 'İleri Seviye Sıcaklık Haritaları ve Hareket Analizi',
    'features.heatmap.description': '• Müşteri hareketleri ve trafik paternlerini görselleştirme\n• En çok ziyaret edilen bölgeleri ve durma noktalarını analiz etme\n• Ürün yerleşimi ve tanıtım alanlarını optimize etme\n• Veri odaklı mağaza dizaynı kararları\n• Sezonsal değişimleri ve kampanya etkilerini takip etme',

    'features.demographics.title': 'Müşteri Demografik Analizi ve Segmentasyon',
    'features.demographics.description': '• KVKK/GDPR uyumlu demografik analiz\n• Yaş, cinsiyet ve ziyaret sıklığı paternlerini takip etme\n• Hedef kitle profillerini netleştirme\n• Pazarlama stratejilerini kişiselleştirme\n• Demografiye dayalı dinamik envanter planlaması',

    'features.staff.title': 'Personel Verimlilik Analizi ve İş Gücü Optimizasyonu',
    'features.staff.description': '• Veri ile objektif performans değerlendirme\n• Vardiya verimliği ve görev dağılımını analiz etme\n• Personel ihtiyaçlarını önceden tahmin etme\n• İş gücü maliyetlerini optimize etme\n• Performans bazlı yönetim sistemleri',

    'features.campaigns.title': 'Kampanya Performans Analizi ve ROI Ölçümleme',
    'features.campaigns.description': '• Detaylı kampanya etkinlik analizi\n• ROI ve dönüşüm oranlarını ölçümleme\n• Müşteri etkileşim metriklerini takip etme\n• Kampanya öncesi, sırası ve sonrası performans karşılaştırması\n• Gelecek kampanyalar için öngörülü öneriler',

    // Use Cases
    'useCases.badge': 'Başarı Hikayeleri',
    'useCases.title': 'Gerçek Dünya Uygulamaları',
    'useCases.subtitle': 'Vislivis\'in retail operasyonlarını pratikte nasıl dönüştürdüğünü görün',
    'useCases.scenario1.title': 'Yoğun Saatlerde Kasiyer Optimizasyonu',
    'useCases.scenario1.description': 'Kuyruk yönetimi ile en yoğun saatleri önceden tahmin ederek yeterli kasiyerin hazır bulunmasını sağlayın, müşteri memnuniyetini artırın.',
    'useCases.scenario1.metric1': 'Bekleme sürelerinde %40 azalma',
    'useCases.scenario1.metric2': 'İyileşmiş müşteri memnuniyeti',
    'useCases.scenario1.metric3': 'Optimize personel tahsisi',
    'useCases.scenario2.title': 'Promosyon Etkinliği Ölçümü',
    'useCases.scenario2.description': 'Kampanya analizi ile yeni bir ürünün veya indirimin mağaza içi trafiği ve satışlara etkisini anında görün.',
    'useCases.scenario2.metric1': 'Gerçek zamanlı kampanya takibi',
    'useCases.scenario2.metric2': 'Anında ROI ölçümü',
    'useCases.scenario2.metric3': 'Trafik patern analizi',
    'useCases.scenario3.title': 'Envanter Optimizasyonu',
    'useCases.scenario3.description': 'Satış ve davranış verilerini birleştirerek hızlı tükenen ürünleri ve stok riski olan ürünleri belirleyin.',
    'useCases.scenario3.metric1': 'Stok tükenmelerinde %30 azalma',
    'useCases.scenario3.metric2': 'Optimize envanter seviyeleri',
    'useCases.scenario3.metric3': 'Öngörülü stok yenileme',

    // Analytics Dashboard
    'analytics.badge': 'Gelişmiş Analitik',
    'analytics.title': 'Gelişmiş Analitik Dashboard',
    'analytics.subtitle': 'Gerçek zamanlı içgörüler ve geçmiş veri analizi',
    'analytics.description': 'Kapsamlı dashboard\'umuz karşılaştırmalı analiz ve öngörülü önerilerle retail operasyonlarınız hakkında detaylı içgörüler sağlar.',
    
    'analytics.comparison.title': 'Dönem Karşılaştırması ve Değişim Takibi',
    'analytics.comparison.description': '• KPI kartlarında yüzdelik değişim göstergeleri (▲ %8 veya ▼ %5)\n• Önceki gün, geçen hafta ve geçen yıl karşılaştırması\n• Kapsamlı trend analizi ve patern tanıma',
    
    'analytics.products.title': 'Ürün Analitiği ve Performans Takibi',
    'analytics.products.description': '• Müşteri etkileşimi ve deneme davranışlarını izleme\n• En yüksek performanslı SKU\'ları ve etkileşim paternlerini tespit\n• Ürün başında geçirilen süre ve etkileşim sıklığı ölçümü\n• Dokunuştan satın almaya dönüşüm hunisi takibi\n• Veri odaklı içgörülerle ürün yerleşimini optimize etme',
    
    'analytics.kpi.title': 'KPI Paneli ve Satış Dönüşüm Analitiği',
    'analytics.kpi.description': '• Kritik iş metriklerine gerçek zamanlı görünürlük\n• Dönüşüm oranları ve işlem değerlerini takip\n• Sepet büyüklüğü ve müşteri edinim maliyeti analizi\n• Geçmiş veriler ve hedeflerle kıyaslama\n• Zaman, ürün ve lokasyona göre gelişmiş segmentasyon',
    
    'analytics.weather.title': 'Hava Durumu İstihbaratı ve Tahmine Dayalı Planlama',
    'analytics.weather.description': '• 15 günlük hava tahmini ve retail etki analizi\n• Ayak trafiğini etkileyen koşullar için otomatik uyarı\n• Proaktif personel ve envanter ayarlamaları\n• Mevsimsel paternler için geçmiş korelasyon analizi\n• Hava tahminlerine dayalı promosyon optimizasyonu',
    
    'analytics.ai.title': 'AI Destekli Öngörülü İstihbarat ve Öneriler',
    'analytics.ai.description': '• Doğal dil işleme ile eyleme dönüştürülebilir içgörüler\n• Gizli paternleri tespit ve gelecek trendlerini öngörme\n• Envanter ve personel için optimal stratejiler\n• Çoklu veri değişkenlerinden bağlamsal içgörüler\n• Performans artışı için regilatif öneriler',

    'analytics.metrics.trafficIncrease': 'Günlük Trafik Artışı',
    'analytics.metrics.processing': 'Gerçek Zamanlı İşleme',
    'analytics.metrics.uptime': 'Çalışma Süresi Garantisi',
    'analytics.metrics.monitoring': 'Sürekli İzleme',

    // Advanced Features
    'advanced.badge': 'Kurumsal Çözümler',
    'advanced.title': 'Gelişmiş Kurumsal Özellikler',
    'advanced.subtitle': 'Modern retail operasyonları için kapsamlı çözümler',
    'advanced.inventory.title': 'Envanter Yönetimi Entegrasyonu',
    'advanced.inventory.description': 'Satış ve davranış verilerini birleştirerek stok yönetiminizi kolaylaştırın, hızlı tükenen ürünleri ve stok riskini önceden belirleyin.',
    'advanced.security.title': 'Gelişmiş Güvenlik ve Gizlilik',
    'advanced.security.description': 'KVKK/GDPR uyumlu veri işleme, gelişmiş anonimleştirme ve kurumsal düzeyde güvenlik protokolleri.',
    'advanced.multistore.title': 'Çoklu Mağaza Yönetimi',
    'advanced.multistore.description': 'Birden fazla mağaza performansını tek panelden yönetin, lokasyonları karşılaştırın ve en iyi uygulamaları belirleyin.',
    'advanced.inventory.benefit1': 'Stok tükenmelerinde %30 azalma',
    'advanced.inventory.benefit2': 'Envanter devir hızı optimizasyonu',
    'advanced.inventory.benefit3': 'Öngörülü stok yenileme uyarıları',
    'advanced.inventory.benefit4': 'Talep tahmini',
    'advanced.security.benefit1': 'KVKK/GDPR uyumluluğu',
    'advanced.security.benefit2': 'Gelişmiş veri anonimleştirme',
    'advanced.security.benefit3': 'Kurumsal düzey şifreleme',
    'advanced.security.benefit4': 'Denetim kaydı tutma',
    'advanced.multistore.benefit1': 'Merkezi yönetim',
    'advanced.multistore.benefit2': 'Lokasyonlar arası analitik',
    'advanced.multistore.benefit3': 'Performans karşılaştırması',
    'advanced.multistore.benefit4': 'En iyi uygulama belirleme',

    // Integrations
    'integrations.badge': 'Sistem Entegrasyonları',
    'integrations.title': 'Sorunsuz Entegrasyonlar',
    'integrations.subtitle': 'Mevcut retail sistemlerinizle bağlantı kurun',
    'integrations.crm.title': 'CRM Entegrasyonu',
    'integrations.crm.description': 'Müşteri verilerini mevcut CRM sistemlerinizle senkronize edin',
    'integrations.erp.title': 'ERP Entegrasyonu',
    'integrations.erp.description': 'Kurumsal kaynak planlama sistemleriyle bağlantı kurun',
    'integrations.pos.title': 'Kasa Entegrasyonu',
    'integrations.pos.description': 'Kasa ve satış noktası sistemleriyle doğrudan entegrasyon',
    'integrations.marketing.title': 'Pazarlama Otomasyonu',
    'integrations.marketing.description': 'Müşteri davranış verilerini pazarlama platformlarına aktararak hedefli kampanyalar yürütün',
    'integrations.bi.title': 'İş Zekası',
    'integrations.bi.description': 'İş zekası ve veri görselleştirme araçlarıyla entegre olarak gelişmiş analitik sağlayın',
    'integrations.hris.title': 'İK ve Doküman Yönetim Sistemi Entegrasyonu',
    'integrations.hris.description': 'İnsan kaynakları ve doküman yönetim sistemleriyle entegrasyon sayesinde personel performansını izinler, vardiya değişiklikleri ve performans değerlendirmeleri ile daha geniş bir perspektiften değerlendirin',
    'integrations.capabilities.title': 'Gelişmiş Entegrasyon Yetenekleri',
    'integrations.capabilities.description': 'Güçlü ve iyi dokümante edilmiş API\'ler, mevcut iş sistemlerinizle sorunsuz entegrasyon sağlar ve retail operasyonlarınızın birleşik görünümünü sunar.',
    'integrations.api.title': 'RESTful API\'ler',
    'integrations.api.description': 'Özel entegrasyonlar için güçlü ve iyi dokümante edilmiş API\'ler',
    'integrations.webhook.title': 'Webhook Desteği',
    'integrations.webhook.description': 'Sistem senkronizasyonu için gerçek zamanlı olay bildirimleri',
    'integrations.formats.title': 'Veri Formatları',
    'integrations.formats.description': 'Esneklik için endüstri standardı JSON ve CSV formatları',
    'integrations.security.title': 'Kurumsal Güvenlik',
    'integrations.security.description': 'Gelişmiş şifreleme ve güvenlik protokolleri',

    // Mobile
    'mobile.badge': 'Mobil Deneyim',
    'mobile.title': 'Mobil Analitik',
    'mobile.subtitle': 'Mağazalarınızı her yerden izleyin',
    'mobile.description': 'Mobil cihazınızdan gerçek zamanlı analitiğe erişin ve anında bildirimler alın.',
    'mobile.notifications': 'Gerçek Zamanlı Bildirimler',
    'mobile.monitoring': 'Canlı Mağaza İzleme',
    'mobile.reports': 'Mobil Raporlar',
    'mobile.alerts': 'Özel Uyarılar',
    'mobile.notifications.description': 'Kuyruk birikmesi, personel verimliliği değişiklikleri ve satış anomalileri için anında uyarılar alın',
    'mobile.monitoring.description': 'Her yerden canlı mağaza analitiği, ısı haritaları ve müşteri akışını izleyin',
    'mobile.reports.description': 'Mobilde detaylı analitik raporlara ve KPI panolarına erişin',
    'mobile.alerts.description': 'Belirli retail metrikleri ve eşikler için özel uyarılar ayarlayın',
    'mobile.distribution.title': 'Kurumsal Dağıtım',
    'mobile.distribution.description': 'Uygulamalar, büyük dağıtımlar için özel markalama ve yapılandırma seçenekleriyle kurumsal kanallar aracılığıyla dağıtılır.',
    'mobile.distribution.ios': 'iOS 14.0+ destekleniyor',
    'mobile.distribution.android': 'Android 9.0+ destekleniyor',
    'mobile.distribution.mdm': 'Kurumsal MDM uyumlu',
    'mobile.distribution.branding': 'Özel markalama mevcut',
    'mobile.distribution.button': 'Kurumsal Erişim Talep Et',

    // Pricing
    'pricing.badge': 'Esnek Çözümler',
    'pricing.title': 'Esnek Fiyatlandırma Planları',
    'pricing.subtitle': 'Retail işletmeniz için mükemmel planı seçin',
    'pricing.starter': 'Başlangıç',
    'pricing.professional': 'Profesyonel',
    'pricing.enterprise': 'Kurumsal',
    'pricing.contactSales': 'Satış İletişim',
    'pricing.scheduleDemo': 'Demo Planlayın',
    'pricing.requestInfo': 'Bilgi Talep Et',
    'pricing.mostPopular': 'En Popüler',
    'pricing.starter.description': 'Analitik ile başlayan küçük retail mağazaları için mükemmel',
    'pricing.starter.feature1': '2 mağaza lokasyonuna kadar',
    'pricing.starter.feature2': 'Temel analitik paneli',
    'pricing.starter.feature3': 'Kuyruk yönetimi',
    'pricing.starter.feature4': 'Müşteri demografisi',
    'pricing.starter.feature5': 'E-posta bildirimleri',
    'pricing.starter.feature6': 'İş saatleri desteği',
    'pricing.professional.description': 'Büyüyen retail işletmeleri için gelişmiş analitik',
    'pricing.professional.feature1': '10 mağaza lokasyonuna kadar',
    'pricing.professional.feature2': 'Gelişmiş ısı haritaları',
    'pricing.professional.feature3': 'Personel verimliliği takibi',
    'pricing.professional.feature4': 'Kampanya analizi',
    'pricing.professional.feature5': 'Hava durumu entegrasyonu',
    'pricing.professional.feature6': 'Mobil uygulama erişimi',
    'pricing.professional.feature7': 'Öncelikli 7/24 destek',
    'pricing.professional.feature8': 'CRM/ERP entegrasyonları',
    'pricing.enterprise.description': 'Büyük zincirler için eksiksiz retail analitik çözümü',
    'pricing.enterprise.feature1': 'Sınırsız mağaza lokasyonu',
    'pricing.enterprise.feature2': 'AI destekli öneriler',
    'pricing.enterprise.feature3': 'Gelişmiş KPI takibi',
    'pricing.enterprise.feature4': 'Özel entegrasyonlar',
    'pricing.enterprise.feature5': 'Yerinde kurulum',
    'pricing.enterprise.feature6': 'Özel destek ekibi',
    'pricing.enterprise.feature7': 'White-label seçenekleri',
    'pricing.enterprise.feature8': 'Gelişmiş güvenlik',
    'pricing.enterprise.feature9': 'Özel raporlama',
    'pricing.custom': 'Özel',
    'pricing.custom.title': 'Özel Kurumsal Çözümler',
    'pricing.custom.description': 'Tüm planlar profesyonel kurulum, eğitim ve sürekli destek içerir. Fiyatlandırma dağıtım büyüklüğü ve özel gereksinimlere göre değişir.',
    'pricing.custom.benefit1': 'Profesyonel Kurulum',
    'pricing.custom.benefit2': '7/24 Teknik Destek',
    'pricing.custom.benefit3': 'Esnek Sözleşmeler',

    // Testimonials
    'testimonials.title': 'Retailcıların Güvendiği',
    'testimonials.subtitle': 'Önde gelen retail markalarının Vislivis\'i nasıl kullandığını görün',
    'testimonials.stats.clients': 'Kurumsal Müşteri',
    'testimonials.stats.uptime': 'Sistem Çalışma Süresi',
    'testimonials.stats.support': 'Destek Kapsamı',
    'testimonials.stats.response': 'Yanıt Süresi',

    // FAQ
    'faq.badge': 'Destek ve Bilgilendirme',
    'faq.title': 'Sıkça Sorulan Sorular',
    'faq.questions': 'Hala sorularınız mı var?',
    'faq.contactTeam': 'Ekibimizle İletişime Geçin',
    'faq.subtitle': 'Vislivis hakkında bilmeniz gereken her şey',
    'faq.q1': 'Kurulum ne kadar sürer?',
    'faq.a1': 'Profesyonel kurulum mağaza büyüklüğü ve kamera sayısına bağlı olarak genellikle yarım gün sürer.',
    'faq.q2': 'Hangi kameralar uyumlu?',
    'faq.a2': 'Vislivis her marka ve model kameraya entegre olur. Minimum gereksinim: 2MP IP kamera.',
    'faq.q3': 'Veriler ne kadar süre saklanır?',
    'faq.a3': 'Tüm veriler lokal olarak işlenir, dışarıya görüntü aktarımı yapılmaz. Analitik veriler ihtiyaçlarınıza göre esnek saklama politikalarıyla 2 yıla kadar saklanır.',
    'faq.q4': 'Sistem KVKK uyumlu mu?',
    'faq.a4': 'Evet, tüm veri işleme gelişmiş anonimleştirme ve gizlilik koruması ile KVKK/GDPR uyumludur.',
    'faq.q5': 'Birden fazla mağazayı yönetebilir miyim?',
    'faq.a5': 'Evet, platformumuz merkezi yönetim ve lokasyonlar arası analitik ile sınırsız mağazayı destekler.',
    'faq.q6': 'Ne tür destek sağlanır?',
    'faq.a6': '7/24 teknik destek, düzenli sistem güncellemeleri ve kurumsal müşteriler için özel hesap yönetimi.',
    'faq.q7': 'Kameralar dışında ek bir donanım gerek var mı?',
    'faq.a7': 'Kameraların görüntülerinin kayıt altına alındığı kayıt sunucusuna ihtiyaç vardır. Yönetilen kamera sayısı ve kullanılacak modül sayısına bağlı olarak sunucu gereksinimleri değişmektedir. Bu konuda detaylı bilgi almak için lütfen bizimle bağlantıya geçiniz.',
    'faq.q8': 'Sistemin hata oranı nedir?',
    'faq.a8': 'Ortalamada %90\'ın üzerinde bir doğruluk oranında çalışmaktadır. Mağazalarda yaptığımız çalışmalarla ilk kurulum sonrasında alınan görüntüler ile kısa sürede bu oranın üzerine çıkabilmektedir.',

    // Contact
    'contact.title': 'Bugün Başlayın',
    'contact.subtitle': 'Retail operasyonlarınızı dönüştürmeye hazır mısınız? Kişiselleştirilmiş demo için bizimle iletişime geçin.',
    'contact.getInTouch': 'İletişime Geçin',
    'contact.phone': 'Telefon',
    'contact.email': 'E-posta',
    'contact.address': 'Adres',
    'contact.sendMessage': 'Mesaj Gönderin',
    'contact.name': 'İsim',
    'contact.company': 'Şirket',
    'contact.message': 'Mesaj',
    'contact.send': 'Mesaj Gönder',
    'contact.hours.title': 'Çalışma Saatleri',
    'contact.hours.weekday': 'Pazartesi - Cuma',
    'contact.hours.weekdayTime': '09:00 - 18:00',
    'contact.hours.saturday': 'Cumartesi',
    'contact.hours.saturdayTime': '10:00 - 16:00',
    'contact.hours.sunday': 'Pazar',
    'contact.hours.sundayTime': 'Kapalı',
    'contact.hours.emergency': 'Acil Destek',
    'contact.hours.emergencyTime': '7/24 Ulaşılabilir',
    'contact.response': 'Genellikle 24 saat içinde yanıt veriyoruz. Acil durumlar için lütfen doğrudan arayın.',

    // Footer
    'footer.description': 'İşletmelerin operasyonlarını optimize etmesine ve satışları artırmasına yardımcı olan AI destekli retail analitik platformu.',
    'footer.products': 'Ürünler',
    'footer.support': 'Destek',
    'footer.company': 'Şirket',
    'footer.certifications': 'Sertifikalarımız',
    'footer.rights': '© 2024 Vislivis. Tüm hakları saklıdır.',
    'footer.products.queue': 'Kuyruk Yönetimi',
    'footer.products.cashier': 'Kasa Analitiği',
    'footer.products.behavior': 'Müşteri Davranışı',
    'footer.products.heatmap': 'Mağaza Isı Haritaları',
    'footer.support.docs': 'Dokümantasyon',
    'footer.support.center': 'Destek Merkezi',
    'footer.support.contact': 'İletişim',
    'footer.support.status': 'Sistem Durumu',
    'footer.company.about': 'Hakkımızda',
    'footer.company.careers': 'Kariyer',
    'footer.company.blog': 'Blog',
    'footer.company.partners': 'Ortaklar',

    // About Section
    'about.title': 'Hakkımızda',
    'about.subtitle': 'Retail operasyonlarını son teknoloji AI ile dönüştürüyoruz',
    
    'about.mission.title': 'Misyonumuz',
    'about.mission.description': 'Perakende sektörünü AI gücüyle dönüştürme misyonuyla yola çıktık. Amacımız, işletmelerin operasyonlarını optimize etmesine, satışları artırmasına ve veri odaklı içgörülerle müşteri memnuniyetini yükseltmesine yardımcı olmaktır.',
    
    'about.vision.title': 'Vizyonumuz',
    'about.vision.description': 'AI destekli retail analitikte küresel lider olmak, gelişmiş teknolojiyi her büyüklükteki işletme için erişilebilir kılmak ve perakendecilerin müşterilerini anlama ve hizmet verme şeklini devrim niteliğinde değiştirmektir.',
    
    'about.story.title': 'Hikayemiz',
    'about.story.paragraph1': 'Vislivis, 2020 yılında retail ortamlarında bilgisayarlı görünün kullanılmayan potansiyelini fark eden AI araştırmacıları ve retail sektörü veteranlarından oluşan bir ekip tarafından kuruldu.',
    'about.story.paragraph2': 'Geleneksel retail analitiğinin kritik davranışsal içgörüleri kaçırdığı basit gözlemiyle başlayarak, müşteri desenlerini daha önce hiç mümkün olmayan şekillerde anlayabilen özel AI algoritmaları geliştirdik.',
    'about.story.paragraph3': 'Bugün dünya çapında 500\'den fazla retail lokasyonuna hizmet veriyor, işletmelerin gerçek zamanlı analitik ve öngörülü içgörülerle daha akıllı kararlar almasına yardımcı oluyoruz.',
    
    'about.values.title': 'Değerlerimiz',
    'about.values.subtitle': 'Yaptığımız her şeye rehberlik eden ilkeler',
    'about.values.innovation.title': 'İnovasyon',
    'about.values.innovation.description': 'Gerçek retail zorluklarını çözmek için AI teknolojisinin sınırlarını sürekli zorluyoruz.',
    'about.values.customer.title': 'Müşteri Odaklılık',
    'about.values.customer.description': 'Geliştirdiğimiz her özellik müşterilerimizin başarısı düşünülerek tasarlanır.',
    'about.values.reliability.title': 'Güvenilirlik',
    'about.values.reliability.description': 'İşletmelerin güvenebileceği tutarlı, doğru sonuçlar sunuyoruz.',
    'about.values.growth.title': 'Büyüme',
    'about.values.growth.description': 'Müşterilerimizin veri odaklı içgörülerle sürdürülebilir büyüme elde etmesine yardımcı oluyoruz.',
    
    'about.why.title': 'Neden Vislivis?',
    'about.why.subtitle': 'Retail analitik alanında bizi farklı kılan özellikler',
    'about.differentiators.accuracy': 'AI Doğruluğu',
    'about.differentiators.speed': 'İşlem Hızı',
    'about.differentiators.stores': 'Aktif Mağaza',
    'about.differentiators.support': 'Destek Kapsamı',
    
    'about.team.title': 'Ekibimiz',
    'about.team.subtitle': 'Vislivis teknolojisinin arkasındaki uzmanlar',
    
    'about.awards.title': 'Ödüller ve Tanınırlık',

    // Live Support
    'support.title': 'Canlı Destek',
    'support.online': 'Şu anda çevrimiçi',
    'support.welcome': 'Merhaba! Vislivis hakkında size nasıl yardımcı olabiliriz?',
    'support.autoResponse': 'Mesajınız için teşekkürler. Ekibimiz en kısa sürede size dönüş yapacak. Acil yardım için lütfen 0216 451 91 12 numarasını arayın.',
    'support.placeholder': 'Mesajınızı yazın...',

    // Terms of Service
    'terms.title': 'Hizmet Şartları',
    'terms.lastUpdated': 'Son Güncelleme',
    'terms.date': '1 Ocak 2025',
    'terms.acceptance.title': '1. Şartların Kabulü',
    'terms.acceptance.content': 'Vislivis hizmetlerine erişerek ve kullanarak, bu Hizmet Şartlarını kabul etmiş ve bunlara bağlı kalmayı taahhüt etmiş olursunuz. Bu şartları kabul etmiyorsanız, lütfen hizmetlerimizi kullanmayınız.',
    'terms.services.title': '2. Hizmetlerin Tanımı',
    'terms.services.content': 'Vislivis, müşteri davranış takibi, kuyruk yönetimi, ürün analitik ve iş zekası araçlarını içeren AI destekli perakende analitik çözümleri sağlar. Hizmetlerimiz abonelik bazında sunulur ve zaman zaman güncellenebilir veya değiştirilebilir.',
    'terms.userResponsibilities.title': '3. Kullanıcı Sorumlulukları',
    'terms.userResponsibilities.content': 'Vislivis hizmetlerinin kullanıcısı olarak şunları kabul edersiniz:',
    'terms.userResponsibilities.item1': 'Kayıt sırasında doğru ve eksiksiz bilgi sağlamak',
    'terms.userResponsibilities.item2': 'Hesap kimlik bilgilerinizin güvenliğini korumak',
    'terms.userResponsibilities.item3': 'Hizmetleri tüm geçerli yasa ve düzenlemelere uygun olarak kullanmak',
    'terms.userResponsibilities.item4': 'Sistemlerimizin güvenliğini veya bütünlüğünü tehlikeye atmaya çalışmamak',
    'terms.intellectualProperty.title': '4. Fikri Mülkiyet Hakları',
    'terms.intellectualProperty.content': 'Vislivis hizmetleri aracılığıyla sağlanan tüm içerik, yazılım, teknoloji ve materyaller Vislivis\'in münhasır mülkiyetidir ve fikri mülkiyet yasaları ile korunmaktadır. Açık yazılı izin olmaksızın kopyalayamaz, değiştiremez, dağıtamaz veya türev eserler oluşturamazsınız.',
    'terms.dataPrivacy.title': '5. Veri Gizliliği ve Güvenliği',
    'terms.dataPrivacy.content': 'Veri gizliliğinizi korumaya kararlıyız. Kişisel verilerin toplanması, kullanılması ve korunması Gizlilik Politikamız tarafından düzenlenir. Hizmetlerimizi kullanarak, Gizlilik Politikasında açıklandığı şekilde veri uygulamalarımıza onay vermiş olursunuz.',
    'terms.limitation.title': '6. Sorumluluk Sınırlaması',
    'terms.limitation.content': 'Vislivis, hizmetlerimizi kullanmanızdan veya kullanamamanızdan kaynaklanan dolaylı, arızi, özel, sonuç olarak ortaya çıkan veya cezalandırıcı zararlardan sorumlu olmayacaktır. Toplam sorumluluğumuz, talepten önceki on iki ayda hizmetler için ödediğiniz tutarı aşmayacaktır.',
    'terms.termination.title': '7. Fesih',
    'terms.termination.content': 'Bu şartların ihlali veya gerekli görülen herhangi bir neden için hizmetlerimize erişiminizi herhangi bir zamanda askıya alma veya sonlandırma hakkını saklı tutarız. Fesih durumunda, hizmetleri kullanma hakkınız derhal sona erecektir.',
    'terms.changes.title': '8. Şartlarda Değişiklikler',
    'terms.changes.content': 'Bu Hizmet Şartlarını herhangi bir zamanda değiştirme hakkını saklı tutarız. Önemli değişiklikler e-posta veya platformumuz aracılığıyla kullanıcılara bildirilecektir. Değişikliklerden sonra hizmetlerin kullanılmaya devam edilmesi, değiştirilen şartların kabul edildiği anlamına gelir.',
    'terms.contact.title': '9. İletişim Bilgileri',
    'terms.contact.content': 'Bu Hizmet Şartları hakkında sorularınız varsa, lütfen bizimle iletişime geçin:',

    // Privacy Policy
    'privacy.title': 'Gizlilik Politikası',
    'privacy.lastUpdated': 'Son Güncelleme',
    'privacy.date': '1 Ocak 2025',
    'privacy.introduction.title': '1. Giriş',
    'privacy.introduction.content': 'Vislivis\'te gizliliğinizi ciddiye alıyoruz. Bu Gizlilik Politikası, perakende analitik platformumuzu ve hizmetlerimizi kullandığınızda bilgilerinizi nasıl topladığımızı, kullandığımızı, açıkladığımızı ve koruduğumuzu açıklar.',
    'privacy.dataCollection.title': '2. Topladığımız Bilgiler',
    'privacy.dataCollection.content': 'Hizmetlerimizi sağlamak ve geliştirmek için çeşitli bilgiler toplarız:',
    'privacy.dataCollection.item1': 'Hesap Bilgileri: İsim, e-posta adresi, şirket detayları ve iletişim bilgileri',
    'privacy.dataCollection.item2': 'Kullanım Verileri: Hizmetlerimizle nasıl etkileşimde bulunduğunuza dair bilgiler',
    'privacy.dataCollection.item3': 'Analitik Verileri: Müşteri davranış paternleri, mağaza performans metrikleri ve operasyonel veriler',
    'privacy.dataCollection.item4': 'Teknik Veriler: IP adresleri, tarayıcı türleri, cihaz bilgileri ve sistem günlükleri',
    'privacy.dataCollection.item5': 'Kamera Verileri: Video görüntüleri ve perakende kameralarından türetilmiş analitik veriler',
    'privacy.dataUsage.title': '3. Bilgilerinizi Nasıl Kullanırız',
    'privacy.dataUsage.content': 'Toplanan bilgileri aşağıdaki amaçlar için kullanırız:',
    'privacy.dataUsage.item1': 'Hizmetlerimizi sağlamak ve sürdürmek',
    'privacy.dataUsage.item2': 'Kullanıcı deneyimini iyileştirmek ve kişiselleştirmek',
    'privacy.dataUsage.item3': 'Hizmetler, güncellemeler ve destek hakkında sizinle iletişim kurmak',
    'privacy.dataUsage.item4': 'Hizmet kalitesini artırmak için kullanım paternlerini analiz etmek',
    'privacy.dataSharing.title': '4. Veri Paylaşımı ve Açıklama',
    'privacy.dataSharing.content': 'Kişisel bilgilerinizi satmıyoruz. Platformumuzu işletmede, iş yürütmede veya kullanıcılarımıza hizmet vermede yardımcı olan, gizlilik anlaşmalarına tabi güvenilir hizmet sağlayıcılarla veri paylaşabiliriz. Ayrıca yasaların gerektirdiği durumlarda veya haklarımızı korumak için bilgileri açıklayabiliriz.',
    'privacy.dataSecurity.title': '5. Veri Güvenliği',
    'privacy.dataSecurity.content': 'Verilerinizi korumak için şifreleme, güvenli sunucular ve erişim kontrolleri dahil endüstri standardı güvenlik önlemleri uyguluyoruz. Ancak, internet üzerinden hiçbir aktarım yöntemi %100 güvenli değildir ve mutlak güvenliği garanti edemeyiz.',
    'privacy.dataRetention.title': '6. Veri Saklama',
    'privacy.dataRetention.content': 'Kişisel verileri, hizmetleri sağlamak ve bu politikada belirtilen amaçları yerine getirmek için gerekli olduğu sürece saklarız. Analitik veriler, geçerli yasalara uygun olarak, tarihsel analiz ve raporlama amacıyla daha uzun süre saklanabilir.',
    'privacy.userRights.title': '7. Haklarınız',
    'privacy.userRights.content': 'Kişisel verilerinizle ilgili aşağıdaki haklara sahipsiniz:',
    'privacy.userRights.item1': 'Erişim: Kişisel verilerinize erişim talep etme',
    'privacy.userRights.item2': 'Düzeltme: Yanlış verilerin düzeltilmesini talep etme',
    'privacy.userRights.item3': 'Silme: Kişisel verilerinizin silinmesini talep etme',
    'privacy.userRights.item4': 'Veri Taşınabilirliği: Yapılandırılmış formatta verilerinizin bir kopyasını talep etme',
    'privacy.cookies.title': '8. Çerezler ve İzleme Teknolojileri',
    'privacy.cookies.content': 'Hizmetlerimizdeki aktiviteyi izlemek ve belirli bilgileri tutmak için çerezler ve benzer izleme teknolojileri kullanırız. Tarayıcınıza çerezleri reddetmesi veya çerez gönderildiğinde bildirmesi talimatını verebilirsiniz. Daha fazla detay için lütfen Çerez Politikamıza bakın.',
    'privacy.changes.title': '9. Gizlilik Politikasında Değişiklikler',
    'privacy.changes.content': 'Bu Gizlilik Politikasını zaman zaman güncelleyebiliriz. Değişiklikleri bu sayfada yeni politikayı yayınlayarak ve "Son Güncelleme" tarihini güncelleyerek size bildireceğiz. Önemli değişiklikler e-posta ile iletilecektir.',
    'privacy.contact.title': '10. Bize Ulaşın',
    'privacy.contact.content': 'Bu Gizlilik Politikası veya veri uygulamalarımız hakkında sorularınız veya endişeleriniz varsa, lütfen bizimle iletişime geçin:',

    // Cookie Policy
    'cookie.title': 'Çerez Politikası',
    'cookie.lastUpdated': 'Son Güncelleme',
    'cookie.date': '1 Ocak 2025',
    'cookie.what.title': '1. Çerezler Nedir',
    'cookie.what.content': 'Çerezler, web sitelerini ziyaret ettiğinizde cihazınızda saklanan küçük metin dosyalarıdır. Web sitelerinin tercihlerinizi hatırlamasına ve tarayıcı deneyiminizi iyileştirmesine yardımcı olurlar. Vislivis, işlevselliği artırmak, kullanımı analiz etmek ve kişiselleştirilmiş deneyimler sağlamak için çerezleri kullanır.',
    'cookie.types.title': '2. Kullandığımız Çerez Türleri',
    'cookie.types.content': 'Çeşitli amaçlar için farklı çerez türleri kullanıyoruz:',
    'cookie.types.essential.title': 'Gerekli Çerezler',
    'cookie.types.essential.content': 'Web sitesinin düzgün çalışması için gereklidir. Bunlar güvenlik, kimlik doğrulama ve erişilebilirlik özellikleri gibi temel işlevselliği etkinleştirir. Bu çerezler olmadan belirli hizmetler sağlanamaz.',
    'cookie.types.performance.title': 'Performans Çerezleri',
    'cookie.types.performance.content': 'Ziyaretçilerin web sitemizle nasıl etkileşimde bulunduğunu, anonim olarak bilgi toplayıp raporlayarak anlamamıza yardımcı olur. Bu veriler web sitesi işlevselliğini ve kullanıcı deneyimini iyileştirmemize yardımcı olur.',
    'cookie.types.functional.title': 'İşlevsel Çerezler',
    'cookie.types.functional.content': 'Tercihlerinizi hatırlama, dil ayarları ve kullanıcı arayüzü özelleştirmeleri gibi gelişmiş işlevsellik ve kişiselleştirme sağlar.',
    'cookie.types.analytics.title': 'Analitik Çerezler',
    'cookie.types.analytics.content': 'Ziyaretçileri tanımamıza ve saymamıza, ziyaretçilerin web sitemizde nasıl hareket ettiğini anlamamıza ve hangi sayfaların en çok ve en az popüler olduğunu belirlememize olanak tanır. Bu, içeriği ve navigasyonu optimize etmemize yardımcı olur.',
    'cookie.usage.title': '3. Çerezleri Nasıl Kullanırız',
    'cookie.usage.content': 'Vislivis çerezleri şunlar için kullanır:',
    'cookie.usage.item1': 'Kullanıcıları doğrulamak ve güvenli oturumlar sürdürmek',
    'cookie.usage.item2': 'Kullanıcı tercihlerini ve ayarlarını hatırlamak',
    'cookie.usage.item3': 'Web sitesi trafiğini ve kullanım paternlerini analiz etmek',
    'cookie.usage.item4': 'Web sitesi performansını ve işlevselliğini iyileştirmek',
    'cookie.thirdParty.title': '4. Üçüncü Taraf Çerezleri',
    'cookie.thirdParty.content': 'Bazı çerezler sayfalarımızda görünen üçüncü taraf hizmetler tarafından yerleştirilir. Analitik ve performans izleme için güvenilir üçüncü taraflar kullanıyoruz. Bu üçüncü tarafların kendi gizlilik politikaları vardır ve çerezleri üzerinde kontrolümüz yoktur.',
    'cookie.control.title': '5. Çerezleri Yönetme',
    'cookie.control.content': 'Çerezleri yönetmek veya devre dışı bırakmak için çeşitli seçenekleriniz vardır:',
    'cookie.control.item1': 'Tarayıcı Ayarları: Çoğu tarayıcı, ayarlar aracılığıyla çerezleri reddetmenize veya mevcut olanları silmenize olanak tanır',
    'cookie.control.item2': 'Çerez Tercihleri: Tercihlerinizi özelleştirmek için çerez onay aracımızı kullanın',
    'cookie.control.item3': 'Vazgeçme Araçları: Analitik ve reklam çerezleri için üçüncü taraf vazgeçme araçlarını kullanın',
    'cookie.changes.title': '6. Çerez Politikasında Değişiklikler',
    'cookie.changes.content': 'Bu Çerez Politikasını uygulamalarımızdaki değişiklikleri veya operasyonel, yasal veya düzenleyici nedenlerle güncelleyebiliriz. Lütfen güncellemeler için bu politikayı periyodik olarak gözden geçirin.',
    'cookie.contact.title': '7. Bize Ulaşın',
    'cookie.contact.content': 'Çerezlerin kullanımımız veya bu Çerez Politikası hakkında sorularınız varsa, lütfen bizimle iletişime geçin:',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};